In [2]:
import pandas as pd
import json
import numpy as np
from unidecode import unidecode

with open('util/comuna2id.json', 'r') as archivo:
    comuna2id = json.load(archivo)

id2comuna = {v: k for k, v in comuna2id.items()}

In [3]:
censo = pd.read_csv('./database/Cantidad-de-Personas-por-Sexo-y-Edad.csv', sep=";")
censo["NOMBRE COMUNA"] = censo["NOMBRE COMUNA"].str.upper()
censo["NOMBRE COMUNA"] = censo["NOMBRE COMUNA"].apply(unidecode)
censo.columns = censo.columns.str.upper()
censo

,ORDEN,NOMBRE REGIÓN,CÓDIGO REGIÓN,NOMBRE PROVINCIA,CÓDIGO PROVINCIA,NOMBRE COMUNA,CÓDIGO COMUNA,EDAD,HOMBRES,MUJERES,TOTAL
0,0,PAÍS,PAÍS,PAÍS,PAÍS,PAIS,PAÍS,Total País,8.601.989,8.972.014,17.574.003
1,1,PAÍS,PAÍS,PAÍS,PAÍS,PAIS,PAÍS,0 a 4,594.059,572.087,1.166.146
2,2,PAÍS,PAÍS,PAÍS,PAÍS,PAIS,PAÍS,5 a 9,618.121,592.068,1.210.189
3,3,PAÍS,PAÍS,PAÍS,PAÍS,PAIS,PAÍS,10 a 14,585.855,561.560,1.147.415
4,4,PAÍS,PAÍS,PAÍS,PAÍS,PAIS,PAÍS,15 a 19,636.064,608.633,1.244.697
...,...,...,...,...,...,...,...,...,...,...,...
7629,7629,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,80 a 84,2,2,4
7630,7630,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,85 a 89,0,1,1
7631,7631,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,90 a 94,0,0,0
7632,7632,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,95 a 99,0,0,0
7633,7633,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,100 o más,0,0,0

In [4]:
farmacia = pd.read_csv("./database/2.-Farmacias-Chile-07.2023.csv", sep=";")
farmacia.columns = farmacia.columns.str.upper()
farmacia["COMUNA"] = farmacia["COMUNA"].str.upper()
farmacia["COMUNA"] = farmacia["COMUNA"].astype("str")
farmacia["COMUNA"] = farmacia["COMUNA"].apply(unidecode)
farmacia.loc[:,"CÓDIGO COMUNA"] = farmacia.loc[:,"COMUNA"].map(comuna2id)
farmacia

,NOMBRE LOCAL,EMPRESA FARMACÉUTICA,EMPRESA RUT,EMPRESA RAZÓN SOCIAL,NÚMERO,TIPO,DIRECCIÓN,REGIÓN,COMUNA,NRO RESOLUCIÓN APERTURA,FECHA RES.,LATITUD,LONGITUD,TIPO RECETARIO,ALOPÁTICA,HOMEOPÁTICA,CÓDIGO COMUNA
0,IBERIA,ALVARADO Y CIA LTDA,79.769.700-1,ALVARADO Y CIA LTDA,0001,FARMACIA PRIVADA,VICTORIA Nº 3092,VALPARAISO,VALPARAISO,343,05/03/1998,"-33,0507822","-71,60297689",INDEPENDIENTE,SI,NO,5101
1,BOTICA UNIÓN,BRUNO MOGGIA GARDELLA Y CIA LTDA,4.567.085-6,BRUNO MOGGIA GARDELLA Y CIA LTDA,0037,FARMACIA PRIVADA,CONDELL 1205,VALPARAISO,VALPARAISO,804,23/04/1997,"-33,04365268","-71,62436012",SIN RECETARIO,SI,NO,5101
2,GALENICA,FARMACIAS GALENICA S.A.,78.925.440-0,FARMACIAS GALENICA S.A.,0010,FARMACIA PRIVADA,ARLEGUI N° 580 L - 7 OF. 201,VALPARAISO,VINA DEL MAR,576,26/02/1998,"-33,0236944","-71,55424005",INDEPENDIENTE,SI,SI,5109
3,GALENICA,FARMACIAS GALENICA S.A.,78.925.440-0,FARMACIAS GALENICA S.A.,0008,FARMACIA PRIVADA,AV. PEDRO MONTT N° 2060,VALPARAISO,VALPARAISO,477,23/07/2008,"-33,04716024","-71,61534274",CENTRALIZADO,SI,SI,5101
4,GALENICA,FARMACIAS GALENICA S.A.,78.925.440-0,FARMACIAS GALENICA S.A.,17,FARMACIA PRIVADA,AMERICO VESPUCIO 7500 LOCAL B3-1B,METROPOLITANA,LA FLORIDA,33126,27/05/2013,"-33,52163","-70,597311",SIN RECETARIO,SI,NO,13110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5288,FARMACIA FARMYMAS,SOCIEDAD FARMACÉUTICA FARMYMAS S.P.A.,77.692.138-6,SOCIEDAD FARMACÉUTICA FARMYMAS S.P.A.,0001,FARMACIA PRIVADA,Llayllay N° 1752,VALPARAISO,VINA DEL MAR,2305201803,16/06/2023,"-33,0153481","-71,5500276",SIN RECETARIO,SI,NO,5109
5289,GrupFarma,Grupfarma,77.626.202-1,Grupfarma S.p.A.,1,FARMACIA PRIVADA,Irarrázaval 4395,METROPOLITANA,NUNOA,1968,24/04/2023,"-33,459518","-70,597858",SIN RECETARIO,SI,NO,13120
5290,OXFAR,OXFAR,77.278.722-7,K&G SPA,1,FARMACIA PRIVADA,"Antonio Bellet 147, local 103",METROPOLITANA,PROVIDENCIA,2932,16/06/2023,"-33,4259493","-70,6175332",SIN RECETARIO,SI,NO,13123
5291,FARMACIA QUINCHAO,FARMACÉUTICAS MI TIERRA SPA,77.531.489-3,FARMACÉUTICAS MI TIERRA SPA,1,FARMACIA PRIVADA,"SERRANO Nº 019, ACHAO",LOS LAGOS,QUINCHAO,2187,16/09/2011,"-42,471176","-73,491798",SIN RECETARIO,SI,NO,10210
5292,FARMACIA FUNDADORES,FARMACIA FUNDADORES,77.732.232-K,FARMACÉUTICA GONZÁLEZ COSGROVE SPA,1,FARMACIA PRIVADA,Avenida Fundadores N° 1090 local 1,VALPARAISO,VALPARAISO,2305300596,29/06/2023,"-33,11963445","-71,57084067",SIN RECETARIO,SI,NO,5101

In [5]:
farmacia[farmacia["CÓDIGO COMUNA"].isna()]
farmacia_limpio = farmacia.dropna(subset="CÓDIGO COMUNA")

censo_x_comuna = censo.drop_duplicates(subset="CÓDIGO COMUNA")
censo_x_comuna.loc[:,'CÓDIGO COMUNA'] = censo_x_comuna.loc[:,'CÓDIGO COMUNA'].replace('PAÍS', np.nan)
censo_x_comuna = censo_x_comuna.dropna(subset="CÓDIGO COMUNA")
censo_x_comuna

,ORDEN,NOMBRE REGIÓN,CÓDIGO REGIÓN,NOMBRE PROVINCIA,CÓDIGO PROVINCIA,NOMBRE COMUNA,CÓDIGO COMUNA,EDAD,HOMBRES,MUJERES,TOTAL
22,22,ARICA Y PARINACOTA,15,ARICA,151,ARICA,15101,Total Comunal,109.389,111.975,221.364
44,44,ARICA Y PARINACOTA,15,ARICA,151,CAMARONES,15102,Total Comunal,726,529,1.255
66,66,ARICA Y PARINACOTA,15,PARINACOTA,152,PUTRE,15201,Total Comunal,2.054,711,2.765
88,88,ARICA Y PARINACOTA,15,PARINACOTA,152,GENERAL LAGOS,15202,Total Comunal,412,272,684
110,110,TARAPACÁ,1,IQUIQUE,11,IQUIQUE,1101,Total Comunal,94.897,96.571,191.468
...,...,...,...,...,...,...,...,...,...,...,...
7524,7524,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,TIERRA DEL FUEGO,123,PORVENIR,12301,Total Comunal,3.993,2.808,6.801
7546,7546,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,TIERRA DEL FUEGO,123,PRIMAVERA,12302,Total Comunal,930,228,1.158
7568,7568,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,TIERRA DEL FUEGO,123,TIMAUKEL,12303,Total Comunal,343,62,405
7590,7590,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,NATALES,12401,Total Comunal,10.992,10.485,21.477
7612,7612,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,Total Comunal,800,409,1.209

In [6]:
comuna_sin_farmacia = censo_x_comuna[~censo_x_comuna["CÓDIGO COMUNA"].isin(farmacia_limpio["CÓDIGO COMUNA"])].drop_duplicates(subset="CÓDIGO COMUNA")
len(comuna_sin_farmacia["NOMBRE COMUNA"])

43

### Cantidad de comunas sin farmacia por region

In [12]:
comuna_sin_farmacia.value_counts(comuna_sin_farmacia["NOMBRE REGIÓN"])
censo_x_comuna[censo_x_comuna["NOMBRE COMUNA"] == "ANCUD"]

,ORDEN,NOMBRE REGIÓN,CÓDIGO REGIÓN,NOMBRE PROVINCIA,CÓDIGO PROVINCIA,NOMBRE COMUNA,CÓDIGO COMUNA,EDAD,HOMBRES,MUJERES,TOTAL
6732,6732,LOS LAGOS,10,CHILOÉ,102,ANCUD,10202,Total Comunal,19.029,19.962,38.991

In [16]:
farmacia_limpio[farmacia_limpio["CÓDIGO COMUNA"] == "10202"]

,NOMBRE LOCAL,EMPRESA FARMACÉUTICA,EMPRESA RUT,EMPRESA RAZÓN SOCIAL,NÚMERO,TIPO,DIRECCIÓN,REGIÓN,COMUNA,NRO RESOLUCIÓN APERTURA,FECHA RES.,LATITUD,LONGITUD,TIPO RECETARIO,ALOPÁTICA,HOMEOPÁTICA,CÓDIGO COMUNA
365,FARMACIA CRUZ VERDE,CRUZ VERDE,89.807.200-2,FARMACIAS CRUZ VERDE S.P.A.,777,FARMACIA PRIVADA,PUDETO Nº254,LOS LAGOS,ANCUD,2575,27/10/2011,"-41,8687706","-73,8270569",SIN RECETARIO,SI,NO,10202
736,FARMACIA DR SIMI,DEL DR. SIMI,59.111.330-5,FARMACIAS DE SIMILARES CHILE S.A.,111,FARMACIA PRIVADA,ELEUTERIO RAMÍREZ Nº 330,LOS LAGOS,ANCUD,588,25/02/2013,"-41,8695296","-73,8258669",SIN RECETARIO,SI,NO,10202
1214,FARMACIA SALCOBRAND,SALCOBRAND,76.031.071-9,SALCOBRAND S.A.,411,FARMACIA PRIVADA,PUDETO Nº301,LOS LAGOS,ANCUD,281,06/02/2009,"-41,8689461","-73,8261185",SIN RECETARIO,SI,NO,10202
1674,FARMACIA AHUMADA,FARMACIAS AHUMADA S.P.A.,76.378.831-8,FARMACIAS AHUMADA S.P.A.,323,FARMACIA PRIVADA,PUDETO Nº289,LOS LAGOS,ANCUD,1934,08/10/2010,"-41,8689651","-73,8260727",SIN RECETARIO,SI,NO,10202
2633,FARMACIA CHILOE,FARMACIA CHILOE,8.205.642-4,ANA VICTORIA SIEGEL MAYORGA,1,FARMACIA PRIVADA,ARTURO PRAT Nº 280,LOS LAGOS,ANCUD,523,15/06/1989,"-41,8674435","-73,8230288",SIN RECETARIO,SI,NO,10202
2634,FARMACIA NUEVA ERA,FARMACIA NUEVA ERA,7.116.189-7,SERGIO ISAAC PILLADO LÓPEZ,1,FARMACIA PRIVADA,ARTURO PRAT 183,LOS LAGOS,ANCUD,862,03/07/2001,"-41,8665733","-73,8279114",SIN RECETARIO,SI,NO,10202
2635,FARMACIA PUDETO,FARMACIA PUDETO,10.247.863-0,CARLOS MAURICIO SIEGUEL TICKE,1,FARMACIA PRIVADA,PUDETO 341 LOCAL 11,LOS LAGOS,ANCUD,219,04/02/2003,"-41,8671989","-73,8295364",SIN RECETARIO,SI,NO,10202
3981,FARMACIA POPULAR ANCUD,CORPORACIÓN MUNICIPAL DE ANCUD,71.420.700-8,CORPORACIÓN MUNICIPAL DE ANCUD,1,FARMACIA POPULAR,"BLANCO ENCALADA N°660, ESQUINA PUDETO, ANCUD",LOS LAGOS,ANCUD,1240,19/07/2019,"-41,8679791","-73,8281557",SIN RECETARIO,SI,NO,10202
4929,FARMACIA LA REBAJA,COMERCIAL PAOLA LAGOS LARA E.I.R.L,77.404.918-5,COMERCIAL PAOLA LAGOS LARA E.I.R.L,31,FARMACIA PRIVADA,"ANIBAL PINTO 312, ANCUD",LOS LAGOS,ANCUD,2147483647,08/06/2022,"-41,86827","-73,82574",SIN RECETARIO,SI,NO,10202

In [18]:
farmacias_x_comuna = farmacia_limpio.value_counts(subset="CÓDIGO COMUNA")
codigo2cantidad_farmacia = farmacias_x_comuna.to_dict()
codigo2cantidad_farmacia

{'13101': 366,
 '13114': 162,
 '13123': 157,
 '13119': 152,
 '5109': 136,
 '13120': 135,
 '13201': 117,
 '8101': 117,
 '7101': 113,
 '2101': 106,
 '13110': 105,
 '5101': 81,
 '9101': 79,
 '6101': 79,
 '4101': 78,
 '13401': 76,
 '1101': 71,
 '15101': 67,
 '13127': 63,
 '10101': 63,
 '13125': 61,
 '7301': 58,
 '13124': 58,
 '13122': 54,
 '8301': 54,
 '5801': 52,
 '13106': 51,
 '13132': 51,
 '13301': 51,
 '13130': 47,
 '8401': 47,
 '8110': 45,
 '4102': 44,
 '10301': 42,
 '13109': 42,
 '13108': 41,
 '14101': 39,
 '13115': 39,
 '13105': 38,
 '13107': 38,
 '3101': 38,
 '13501': 35,
 '13113': 35,
 '2201': 35,
 '5601': 34,
 '12101': 32,
 '5804': 32,
 '7401': 32,
 '13104': 32,
 '13126': 31,
 '13605': 30,
 '5301': 30,
 '5501': 29,
 '4301': 28,
 '13103': 27,
 '6301': 27,
 '13402': 27,
 '13118': 26,
 '13117': 25,
 '13601': 25,
 '13128': 24,
 '10109': 24,
 '8108': 24,
 '9120': 23,
 '13102': 22,
 '13129': 21,
 '5701': 21,
 '13121': 21,
 '10201': 20,
 '1107': 20,
 '5103': 20,
 '5502': 19,
 '5401': 19,
 '13604': 19,
 '5802': 18,
 '8102': 18,
 '8112': 18,
 '6108': 17,
 '13302': 17,
 '13111': 17,
 '13112': 17,
 '6115': 17,
 '6310': 16,
 '13131': 16,
 '9201': 15,
 '9115': 14,
 '6117': 14,
 '7406': 14,
 '7102': 14,
 '8111': 13,
 '3301': 13,
 '7201': 13,
 '7304': 12,
 '7404': 12,
 '11101': 12,
 '4201': 12,
 '13404': 12,
 '7105': 11,
 '5107': 11,
 '8202': 10,
 '6201': 10,
 '8303': 10,
 '8103': 10,
 '9211': 10,
 '13116': 10,
 '8203': 9,
 '8416': 9,
 '7109': 9,
 '5604': 9,
 '8106': 9,
 '13603': 9,
 '10202': 9,
 '5102': 9,
 '4204': 9,
 '8107': 8,
 '8304': 8,
 '8306': 8,
 '8313': 8,
 '6107': 8,
 '14201': 8,
 '14108': 8,
 '9108': 7,
 '8312': 7,
 '13602': 7,
 '7402': 7,
 '5602': 7,
 '5603': 7,
 '5605': 7,
 '8201': 7,
 '13403': 7,
 '4203': 7,
 '4106': 7,
 '12401': 7,
 '5402': 6,
 '5703': 6,
 '13503': 6,
 '5803': 6,
 '6303': 6,
 '6116': 6,
 '9109': 6,
 '7302': 6,
 '14204': 6,
 '5105': 6,
 '9112': 6,
 '10208': 6,
 '3202': 6,
 '8205': 6,
 '8305': 6,
 '11201': 5,
 '9203': 5,
 '8311': 5,
 '3201': 5,
 '9114': 5,
 '9111': 5,
 '9202': 5,
 '5606': 5,
 '10102': 5,
 '8206': 5,
 '6106': 5,
 '10105': 5,
 '2301': 5,
 '6307': 4,
 '8413': 4,
 '9210': 4,
 '8405': 4,
 '6113': 4,
 '8404': 4,
 '8109': 4,
 '10107': 4,
 '7303': 4,
 '7305': 4,
 '7308': 4,
 '7403': 4,
 '6110': 4,
 '10303': 4,
 '7107': 4,
 '5504': 4,
 '3102': 4,
 '14104': 4,
 '14107': 4,
 '13202': 4,
 '13303': 4,
 '5705': 4,
 '5506': 4,
 '8406': 3,
 '8402': 3,
 '7202': 3,
 '4303': 3,
 '10307': 3,
 '7307': 3,
 '13504': 3,
 '14106': 3,
 '14103': 3,
 '10108': 3,
 '5201': 3,
 '10203': 3,
 '10205': 3,
 '7407': 3,
 '7408': 3,
 '5405': 3,
 '8105': 3,
 '8414': 3,
 '8421': 3,
 '10106': 3,
 '6111': 3,
 '6112': 3,
 '6105': 3,
 '6114': 3,
 '2102': 3,
 '2104': 3,
 '14202': 3,
 '9119': 3,
 '5403': 3,
 '13502': 3,
 '9102': 3,
 '9107': 3,
 '3304': 3,
 '6305': 3,
 '3103': 2,
 '9206': 2,
 '5303': 2,
 '14105': 2,
 '4302': 2,
 '2203': 2,
 '10104': 2,
 '8307': 2,
 '9110': 2,
 '8310': 2,
 '8309': 2,
 '9117': 2,
 '6109': 2,
 '1401': 2,
 '12301': 2,
 '7103': 2,
 '7110': 2,
 '13203': 2,
 '7203': 2,
 '5702': 2,
 '7306': 2,
 '6204': 2,
 '6203': 2,
 '6206': 2,
 '10302': 2,
 '10305': 2,
 '10210': 2,
 '6104': 2,
 '7405': 2,
 '14203': 2,
 '6103': 2,
 '9121': 1,
 '10103': 1,
 '8419': 1,
 '10403': 1,
 '11203': 1,
 '9103': 1,
 '9105': 1,
 '11301': 1,
 '6308': 1,
 '6304': 1,
 '9209': 1,
 '9118': 1,
 '6302': 1,
 '11401': 1,
 '6102': 1,
 '9113': 1,
 '9208': 1,
 '9207': 1,
 '2302': 1,
 '8417': 1,
 '6205': 1,
 '9204': 1,
 '8104': 1,
 '7106': 1,
 '4304': 1,
 '10209': 1,
 '5304': 1,
 '10207': 1,
 '10304': 1,
 '13505': 1,
 '8204': 1,
 '1403': 1,
 '1404': 1,
 '5104': 1,
 '8302': 1,
 '5503': 1,
 '1405': 1,
 '10306': 1,
 '7309': 1,
 '4103': 1,
 '8308': 1,
 '10401': 1,
 '10402': 1,
 '8314': 1,
 '4202': 1,
 '8403': 1,
 '5706': 1,
 '4105': 1,
 '7108': 1,
 '8408': 1,
 '8409': 1,
 '5404': 1,
 '8412': 1,
 '8411': 1}

In [23]:
farmacias_x_comuna.isna().any()

False

In [25]:
codigo2cantidad_farmacia.get(12201)

In [28]:
censo_x_comuna.loc[:, "CANTIDAD FARMACIA"] = censo_x_comuna.loc[:,"CÓDIGO COMUNA"].map(codigo2cantidad_farmacia)
censo_x_comuna.loc[:, "CANTIDAD FARMACIA"] = censo_x_comuna.loc[:, "CANTIDAD FARMACIA"].replace(np.nan, 0)
censo_x_comuna
censo_x_comuna.sort_values(by="CANTIDAD FARMACIA", ascending=False)

,ORDEN,NOMBRE REGIÓN,CÓDIGO REGIÓN,NOMBRE PROVINCIA,CÓDIGO PROVINCIA,NOMBRE COMUNA,CÓDIGO COMUNA,EDAD,HOMBRES,MUJERES,TOTAL,CANTIDAD FARMACIA
1826,1826,METROPOLITANA DE SANTIAGO,13,SANTIAGO,131,SANTIAGO,13101,Total Comunal,206.678,197.817,404.495,366.0
2112,2112,METROPOLITANA DE SANTIAGO,13,SANTIAGO,131,LAS CONDES,13114,Total Comunal,135.917,158.921,294.838,162.0
2310,2310,METROPOLITANA DE SANTIAGO,13,SANTIAGO,131,PROVIDENCIA,13123,Total Comunal,65.710,76.369,142.079,157.0
2222,2222,METROPOLITANA DE SANTIAGO,13,SANTIAGO,131,MAIPU,13119,Total Comunal,250.792,270.835,521.627,152.0
1122,1122,VALPARAÍSO,5,VALPARAÍSO,51,VINA DEL MAR,5109,Total Comunal,158.669,175.579,334.248,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6776,6776,LOS LAGOS,10,CHILOÉ,102,CURACO DE VELEZ,10204,Total Comunal,1.853,1.976,3.829,0.0
1672,1672,VALPARAÍSO,5,SAN FELIPE DE ACONCAGUA,57,PANQUEHUE,5704,Total Comunal,3.677,3.596,7.273,0.0
968,968,COQUIMBO,4,LIMARÍ,43,RIO HURTADO,4305,Total Comunal,2.138,2.140,4.278,0.0
4752,4752,BIOBÍO,8,ARAUCO,82,TIRUA,8207,Total Comunal,5.195,5.222,10.417,0.0
7612,7612,MAGALLANES Y DE LA ANTÁRTICA CHILENA,12,ÚLTIMA ESPERANZA,124,TORRES DEL PAINE,12402,Total Comunal,800,409,1.209,0.0

In [34]:
censo_x_comuna.loc[:,"TOTAL"] = censo_x_comuna.loc[:,"TOTAL"].str.replace(".", "").astype("int")
pv = pd.pivot_table(censo_x_comuna, index=['NOMBRE REGIÓN'], values=['CANTIDAD FARMACIA', "TOTAL"],aggfunc=np.sum).reset_index()
pv.sort_values(by="CANTIDAD FARMACIA", ascending=False)

                                NOMBRE REGIÓN  CANTIDAD FARMACIA    TOTAL
12                  METROPOLITANA DE SANTIAGO             2439.0  7112808
14                                 VALPARAÍSO              600.0  1815902
4                                      BIOBÍO              510.0  2037414
11                                      MAULE              346.0  1044950
7       LIBERTADOR GENERAL BERNARDO O'HIGGINS              249.0   914555
8                                   LOS LAGOS              213.0   828708
6                                LA ARAUCANÍA              208.0   957224
5                                    COQUIMBO              194.0   757586
0                                 ANTOFAGASTA              155.0   607534
13                                   TARAPACÁ               96.0   330558
9                                    LOS RÍOS               82.0   384837
2                                     ATACAMA               71.0   286168
1                          ARICA Y PARINACOTA               67.0   226068
10       MAGALLANES Y DE LA ANTÁRTICA CHILENA               41.0   166533
3   AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO               20.0   103158

In [40]:
pv.loc[:, "FARMACIA X HABITANTE"] = pv.loc[:, "TOTAL"] / pv.loc[:, "CANTIDAD FARMACIA"]
pv.loc[:, "FARMACIA X HABITANTE"] = pv.loc[:, "FARMACIA X HABITANTE"].apply(int)
pv
pv.sort_values(by="FARMACIA X HABITANTE")

,NOMBRE REGIÓN,CANTIDAD FARMACIA,TOTAL,FARMACIA X HABITANTE
12,METROPOLITANA DE SANTIAGO,2439.0,7112808,2916
11,MAULE,346.0,1044950,3020
14,VALPARAÍSO,600.0,1815902,3026
1,ARICA Y PARINACOTA,67.0,226068,3374
13,TARAPACÁ,96.0,330558,3443
7,LIBERTADOR GENERAL BERNARDO O'HIGGINS,249.0,914555,3672
8,LOS LAGOS,213.0,828708,3890
5,COQUIMBO,194.0,757586,3905
0,ANTOFAGASTA,155.0,607534,3919
4,BIOBÍO,510.0,2037414,3994
2,ATACAMA,71.0,286168,4030
10,MAGALLANES Y DE LA ANTÁRTICA CHILENA,41.0,166533,4061
6,LA ARAUCANÍA,208.0,957224,4602
9,LOS RÍOS,82.0,384837,4693
3,AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO,20.0,103158,5157

In [42]:
columna = pv["FARMACIA X HABITANTE"]

# Calcula la media y la desviación estándar de la columna
media = columna.mean()
desviacion_estandar = columna.std()

# Normaliza los datos utilizando z-score
columna_normalizada = (columna - media) / desviacion_estandar

# Ahora, puedes calcular la desviación estándar de los datos normalizados
desviacion_estandar_normalizada = columna_normalizada.std()
desviacion_estandar_normalizada

1.0